version: 1.0.{build}
build: off
test_script:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'
    
    write-host $env:APPVEYOR_JOB_ID
    
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/o29855j66xp53gvn", (Resolve-Path .\nunit-result.xml))
