version: 1.0.{build}
build: off
test_script:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'
  
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nunit-result.xml))
