version: 1.0.{build}
build: off
test_script:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'
    
    write-host $env:APPVEYOR_JOB_ID
    
    #$wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$env:APPVEYOR_JOB_ID", (Resolve-Path .\nunit-result.xml))
    
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID", (Resolve-Path .\WDIO.xunit.chrome.0-0.xml))